#!/bin/bash
PREFIX="../../microservices/microservice-ethereum/server/contracts/tezos"
docker run --rm -v "$PWD":"$PWD" -w "$PWD" ligolang/ligo:0.19.0 compile-contract --michelson-format=json ligo/rules/AddressThresholdLockRule.ligo main > "$PREFIX/AddressThresholdLockRule.json"
docker run --rm -v "$PWD":"$PWD" -w "$PWD" ligolang/ligo:0.19.0 compile-contract --michelson-format=json ligo/rules/SoftTransferLimitRule.ligo main > "$PREFIX/SoftTransferLimitRule.json"
docker run --rm -v "$PWD":"$PWD" -w "$PWD" ligolang/ligo:0.19.0 compile-contract --michelson-format=json ligo/operating/ComplianceRegistry.ligo main > "$PREFIX/ComplianceRegistry.json"
docker run --rm -v "$PWD":"$PWD" -w "$PWD" ligolang/ligo:0.19.0 compile-contract --michelson-format=json ligo/rules/UserAttributeValidToRule.ligo main > "$PREFIX/UserAttributeValidToRule.json"
docker run --rm -v "$PWD":"$PWD" -w "$PWD" ligolang/ligo:0.19.0 compile-contract --michelson-format=json ligo/rules/GlobalFreezeRule.ligo main > "$PREFIX/GlobalFreezeRule.json"
docker run --rm -v "$PWD":"$PWD" -w "$PWD" ligolang/ligo:0.19.0 compile-contract --michelson-format=json ligo/rules/UserFreezeRule.ligo main > "$PREFIX/UserFreezeRule.json"
docker run --rm -v "$PWD":"$PWD" -w "$PWD" ligolang/ligo:0.19.0 compile-contract --michelson-format=json ligo/rules/HardTransferLimitRule.ligo main > "$PREFIX/HardTransferLimitRule.json"
docker run --rm -v "$PWD":"$PWD" -w "$PWD" ligolang/ligo:0.19.0 compile-contract --michelson-format=json ligo/rules/UserKycThresholdBothRule.ligo main > "$PREFIX/UserKycThresholdBothRule.json"
docker run --rm -v "$PWD":"$PWD" -w "$PWD" ligolang/ligo:0.19.0 compile-contract --michelson-format=json ligo/rules/MaxTransferRule.ligo main > "$PREFIX/MaxTransferRule.json"
docker run --rm -v "$PWD":"$PWD" -w "$PWD" ligolang/ligo:0.19.0 compile-contract --michelson-format=json ligo/rules/UserKycThresholdFromRule.ligo main > "$PREFIX/UserKycThresholdFromRule.json"
docker run --rm -v "$PWD":"$PWD" -w "$PWD" ligolang/ligo:0.19.0 compile-contract --michelson-format=json ligo/rules/MinTransferRule.ligo main > "$PREFIX/MinTransferRule.json"
docker run --rm -v "$PWD":"$PWD" -w "$PWD" ligolang/ligo:0.19.0 compile-contract --michelson-format=json ligo/rules/UserKycThresholdToRule.ligo main > "$PREFIX/UserKycThresholdToRule.json"
docker run --rm -v "$PWD":"$PWD" -w "$PWD" ligolang/ligo:0.19.0 compile-contract --michelson-format=json ligo/operating/RuleEngine.ligo main > "$PREFIX/RuleEngine.json"
docker run --rm -v "$PWD":"$PWD" -w "$PWD" ligolang/ligo:0.19.0 compile-contract --michelson-format=json ligo/rules/UserValidRule.ligo main > "$PREFIX/UserValidRule.json"
docker run --rm -v "$PWD":"$PWD" -w "$PWD" ligolang/ligo:0.19.0 compile-contract --michelson-format=json ligo/token/ShareBridgeToken.ligo main > "$PREFIX/ShareBridgeToken.json"